version: 0.2

phases:
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm set-script prepare ""
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling TypeScript
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - 'node_modules/**/*'
    - 'dist/**/*'
    - 'build/**/*'
    - 'prisma/**/*'
    - 'package.json'
    - 'package-lock.json'
    - '.npmrc'
